spring.application.name=notepad-backend

spring.datasource.url=jdbc:postgresql://db.glefovwqsvxolyjjxzlv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=G?EatBc4YxzYVML

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect